#!/bin/sh
set -e

OS=$(lsb_release -i -s)
UV=$(lsb_release -r -s)

if [ "$OS" = "Ubuntu" ]
then
	if [ "$UV" = "22.04" ]
	then
		cp -f openssl-conf/Ubuntu22_04/openssl.cnf debian/strongswan/etc/ssl/openssl.cnf.mlnx
	else
		cp -f openssl-conf/Ubuntu20_04/openssl.cnf debian/strongswan/etc/ssl/openssl.cnf.mlnx
	fi
elif [ "$OS" = "Debian" ]
then
	cp -f openssl-conf/Debian10/openssl.cnf debian/strongswan/etc/ssl/openssl.cnf.mlnx
fi

cp -f mlnx-conf/BFL.swanctl.conf debian/strongswan/etc/swanctl/conf.d
cp -f mlnx-conf/BFR.swanctl.conf debian/strongswan/etc/swanctl/conf.d
