#!/bin/sh
set -e

OS=$(lsb_release -i -s)
UV=$(lsb_release -r -s)

cp -f mlnx-conf/BFL.swanctl.conf debian/strongswan/etc/swanctl/conf.d
cp -f mlnx-conf/BFR.swanctl.conf debian/strongswan/etc/swanctl/conf.d
