module(
	name = "strongswan-qrypt",
	version = "0.0.0.rpg.version.placeholder",
	compatibility_level = 1,
)

bazel_dep(name = "rules_foreign_cc", version = "0.15.0")
bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "bazel_skylib", version = "1.8.2")

register_toolchains(
		"//tools/toolchains:cc_toolchain_for_linux_x86_64",  # cross compile arm -> x86
)

http_archive = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "hiredis-repo",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
filegroup(name=\"hiredis-src\", srcs=glob([\"**\"]))
""",
    sha256 = "25cee4500f359cf5cad3b51ed62059aadfc0939b05150c1f19c7e2829123631c",
    strip_prefix = "hiredis-1.3.0",
    type = "tar.gz",
    urls = ["https://github.com/redis/hiredis/archive/refs/tags/v1.3.0.tar.gz"],
)

http_archive(
    name = "liboqs-repo",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
filegroup(name=\"liboqs-src\", srcs=glob([\"**\"]))
""",
    sha256 = "5b0df6138763b3fc4e385d58dbb2ee7c7c508a64a413d76a917529e3a9a207ea",
    strip_prefix = "liboqs-0.14.0",
    type = "tar.gz",
    urls = ["https://github.com/open-quantum-safe/liboqs/archive/refs/tags/0.14.0.tar.gz"],
)
