# Include config snippets
include conf.d/*.conf

conn-defaults 
{
  unique = replace
  reauth_time = 0
  version = 2
  mobike = no
  proposals = aes128-sha256-x25519
}

child-defaults 
{
  esp_proposals = aes256gcm16-modp2048-ke1_blast-esn
  mode = transport
  policies_fwd_out = yes
  start_action = start
}

connections 
{
  tun-1 : conn-defaults
  {
    local_addrs  = 0.0.0.0/0
    remote_addrs = REMOTE_ADDR
    local 
    {
      auth = psk
      id = LOCAL_ADDR
    }
    remote 
    {
      auth = psk
      id = REMOTE_ADDR
    }
    children 
    {
      tun-in-1 : child-defaults 
      {
        local_ts = LOCAL_ADDR/24 [udp/4789]
        remote_ts = REMOTE_ADDR/24 [udp]
      }
      tun-out-1 : child-defaults 
      {
        local_ts = LOCAL_ADDR/24 [udp]
        remote_ts = REMOTE_ADDR/24 [udp/4789]
      }
    }
  }
}

secrets 
{
  ike-tun 
  {
    id = LOCAL_ADDR
    secret = SHARED_SECRET
  }
}
